version: '2'

services:
    nginx: 
        restart: unless-stopped
        container_name: demo_nginx
        build:
            context: .
            dockerfile: ./Dockerfile.nginx
        ports:
            - 80:80
        volumes:
<<<<<<< HEAD
            - ./django_project/django_static:/app/backend/server/django_static
=======
            - static_volume:/app/backend/server/django_static
>>>>>>> 04c2c0321e325d2f41bf2df6f90741e5d0fb2861
            - ./django_project/media:/app/backend/server/media
            - ./nginx/development:/etc/nginx/conf.d

    rmq:
        image: rabbitmq:3.10-management
        restart: always
        container_name: demo_rmq
        environment:
          - RABBITMQ_DEFAULT_USER=${RMQ_USER}
          - RABBITMQ_DEFAULT_PASS=${RMQ_PASS}
        volumes:
          - rabbitmq_data_volume:/var/lib/rabbitmq/
        ports:
          - 1234:15672
          - 5671-5672:5671-5672
        env_file:
            - ./.env

volumes:
<<<<<<< HEAD
=======
    static_volume: {}
>>>>>>> 04c2c0321e325d2f41bf2df6f90741e5d0fb2861
    rabbitmq_data_volume: {}
